//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBClientAlertItemTestRecipe.h"

@interface SBClientAlertItemTestRecipe (SBAssistantAlerts)
- (id)_currentAssistantLanguage;
- (void)educationAlertWasDeactivated:(id)arg1;
- (id)_assistantEducationAlert;
@end

