//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBClientAlertItemTestRecipe.h"

@interface SBClientAlertItemTestRecipe (SBWiFiPickerAlerts)
- (id)_wifiTrustAlert;
- (id)_wifiPasswordAlert;
- (id)_wifiIsEnterpriseAlert;
- (id)_wifiErrorAlert;
- (id)_wifiDontAskAlert;
- (id)_wifiBTSSPAlert;
@end

