//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBSnapshotDataProvider.h"

@class NSString, SBSnapshotDataProviderContext, UIScreen;

@interface SBIOSurfacePNGSnapshotDataProvider : NSObject <SBSnapshotDataProvider>
{
    struct __IOSurface *_surface;
    SBSnapshotDataProviderContext *_context;
    _Bool _shouldRotate;
    UIScreen *_screen;
}

@property(readonly, retain, nonatomic) SBSnapshotDataProviderContext *context; // @synthesize context=_context;
- (id)fetchData;
- (void)dealloc;
- (id)initWithIOSurfaceRef:(struct __IOSurface *)arg1 screen:(id)arg2 context:(id)arg3 shouldRotate:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

