//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIController.h"

@interface SBUIController (SBUIAnimationController)
+ (void)_addStatusBarToZoomView:(id)arg1 forApplication:(id)arg2 interfaceOrientation:(long long)arg3 inJailRect:(struct CGRect)arg4;
+ (id)_zoomViewWithIOSurfaceSnapshotOfApp:(id)arg1 sceneID:(id)arg2 screen:(id)arg3 includeStatusBar:(_Bool)arg4;
+ (id)_zoomViewForApplication:(id)arg1 sceneID:(id)arg2 screen:(id)arg3 interfaceOrientation:(long long)arg4 includeStatusBar:(_Bool)arg5 snapshotFrame:(struct CGRect *)arg6 decodeImage:(_Bool)arg7;
+ (id)_zoomViewWithSplashboardLaunchImageForApplication:(id)arg1 sceneID:(id)arg2 screen:(id)arg3 interfaceOrientation:(long long)arg4 includeStatusBar:(_Bool)arg5 snapshotFrame:(struct CGRect *)arg6;
+ (id)_zoomViewForApplication:(id)arg1 sceneID:(id)arg2 screen:(id)arg3 image:(id)arg4 interfaceOrientation:(long long)arg5 originalImageOrientation:(long long)arg6 currentImageOrientation:(long long)arg7 includeStatusBar:(_Bool)arg8 snapshotFrame:(struct CGRect *)arg9 decodeImage:(_Bool)arg10;
+ (id)zoomViewForContextHostView:(id)arg1 application:(id)arg2 sceneID:(id)arg3 includeStatusBar:(_Bool)arg4;
+ (id)zoomViewForApplication:(id)arg1 sceneID:(id)arg2 includeStatusBar:(_Bool)arg3 decodeImage:(_Bool)arg4;
+ (id)rawZoomViewForApplication:(id)arg1 sceneID:(id)arg2 onScreen:(id)arg3;
+ (struct CGRect)snapshotRectForOrientation:(long long)arg1 statusBarStyleRequest:(id)arg2 hidden:(_Bool)arg3;
@end

